.\" -*- nroff -*-
.\"
.\" fuse.1: Fuse man page
.\" Copyright (c) 2001,2002 Russell Marks, Philip Kendall, Darren Salt
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.\"
.\" Author contact information:
.\"
.\" E-mail: pak21-fuse@srcf.ucam.org
.\" Postal address: 15 Crescent Road, Wokingham, Berks, RG40 2DB, England
.\"
.\"
.TH fuse 1 "17th August, 2002" "Version 0.5.0" "Emulators"
.\"
.\"------------------------------------------------------------------
.\"
.SH NAME
fuse \- Sinclair ZX Spectrum emulator
.\"
.\"------------------------------------------------------------------
.\"
.SH SYNOPSIS
.\" the trend for long-option-using programs is to give a largely
.\" generic synopsis, so...
.PD 0
.B fuse
.RI [ options ]
.P
.PD 1
.\"
.\"------------------------------------------------------------------
.\"
.SH DESCRIPTION
Fuse is a Sinclair ZX Spectrum emulator. It supports several models
(including the 128), with quite faithful emulation of the display and
sound.
.PP
The emulator can load Z80 and SNA snapshots, and TAP and TZX
virtual-tape files. Saving to both Z80 snapshots and TZX tape files is
supported. The SLT extension to the Z80 format is partly supported
(enough for multi-load games); however, loading of the old DAT-file
variant is not. DSK disk images are supported when emulating a +3.
.PP
There is also support for reading and writing the RZX input recording
format.
.\"
.\"------------------------------------------------------------------
.\"
.SH OPTIONS
.\" dual short/long option listings here reflect the GNU approach,
.\" as used in info files. It does mean using RS/RE, though,
.\" so this is used for all options (for consistency).
.\"
.\" the options list is in alphabetical order by long option name (or
.\" short option name if none).
.\"
.I -h
.br
.I --help
.RS
Give brief usage help, listing available options.
.RE
.PP
.I --issue2
.RS
Emulate an issue 2 keyboard. Same as the General Options dialog's
.I "Issue 2 keyboard"
option.
.RE
.PP
.I --kempston
.RS
Emulate a Kempston joystick. Same as the General Options dialog's
.I "Kempston joystick"
option.
.RE
.PP
.I "-m type"
.br
.I "--machine type"
.RS
Specify machine type to emulate initially. The default is
.IR 48 ,
a 48K Spectrum. The available options are
.IR 48 ,
.IR 128 ,
.IR plus2 ,
.IR plus2a ,
.IR plus3 ,
and
.IR 2048 .
.RE
.PP
.I "-o long_option"
.RS
Equivalent to
.RI ` --long_option '.
If
.I getopt_long
was not present when Fuse was compiled, this will be the only way of
using long options on the command line.
.RE
.PP
.I "-p file"
.br
.I "--playback file"
.RS
Specify an RZX file to begin playback from.
.RE
.PP
.I "-r file"
.br
.I "--record file"
.RS
Specify an RZX file to begin recording to.
.RE
.PP
.I --separation
.RS
Give stereo separation of the 128's AY sound channels. Same as the
General Options dialog's
.I "AY stereo separation"
option.
.RE
.PP
.I --slt
.RS
Support the SLT trap instruction. (Enabled by default, but you can use
.RI ` --no-slt '
to disable.) Same as the General Options dialog's
.I "Use .slt traps"
option.
.RE
.PP
.I "-s file"
.br
.I "--snapshot file"
.RS
Specify a snapshot file to load. The file must be in Z80,
SNA, or SLT format.
.RE
.PP
.I "-d device"
.br
.I "--sound-device device"
.RS
Specify the sound output device to use. Generally you shouldn't need
to specify this, but it might be useful if you have more than one.
.RE
.PP
.I "-v mode"
.br
.I "--svga-mode mode"
.RS
Specify which mode to use for the SVGAlib UI. Available values for
.I mode
are `320' (which corresponds to a 320x240x256 mode), the default and
`640' (a 640x480x256 mode).
.RE
.PP
.I "-t file"
.br
.I "--tape file"
.RS
Specify a virtual tape file to use. It must be in TAP or TZX format.
Note that unlike snapshots, tape files are
.I not
automatically loaded, even if specified on the command line.
.RE
.PP
.I --traps
.RS
Support traps for ROM tape loading/saving. (Enabled by default, but
you can use
.RI ` --no-traps '
to disable.) Same as the General Options dialog's
.I "Use tape traps"
option.
.RE
.PP
.I -V
.br
.I --version
.RS
Show which version of Fuse is being used.
.RE
.PP
All long options which control on/off settings can be disabled using
.RI ` --no-foo '
(for an option
.RI ` --foo ').
For example, the opposite of
.RI ` --issue2 '
is
.RI ` --no-issue2 '.
These options can also be modified while the emulator is running,
using the General Options dialog - see the documentation for the
.I Options, General...
menu item in the
.B "MENUS AND KEYS"
section for details.
.PP
Long options listed above will not be present if the
.I getopt_long
function was not available when Fuse was compiled, but the
.RI ` -o '
option should allow you to use them all the same.
.\"
.\"------------------------------------------------------------------
.\"
.SH "THE VARIOUS FRONT-ENDS"
Fuse supports various front-ends, or UIs (user interfaces). The usual
one is GTK+-based, but there are also Xlib and svgalib ones, as well
as some more experimental options for the adventurous. :-)
.PP
The important difference to note is that the GTK+ version uses
`native' dialog boxes etc. (behaving like a fairly normal GUI-based
program) while the others use an alternative, Fuse-specific `widget
UI'. This latter front-end is easily spotted by the way it uses the
main Fuse window/screen for menus and dialogs, and uses the Spectrum's
own font.
.\"
.\"------------------------------------------------------------------
.\"
.SH "MENUS AND KEYS"
Since many of the keys available are devoted to emulation of the
Spectrum's keyboard, the primary way of controlling Fuse itself
(rather than the emulated machine) is via the menus. There are also
function key shortcuts for some menu options.
.PP
In the GTK+ version, the menu bar is always visible at the top of the
Fuse window. You can click on a menu name to pop it up. Alternatively,
you can press
.I F1
to display a pop-up version of the menu bar, which you can then
navigate with the cursor keys or mouse.
.PP
In the widget UI pressing
.I F1
is the only way to get the main menu; and unlike the GTK+ version, the
emulator pauses while the menus are being navigated. The menus show
which key to press for each menu option in brackets. Pressing
.I Esc
exits a menu, and pressing
.I Enter
exits the menu system entirely (as well as `confirming' any current
dialog).
.PP
Here's what the menu options do, along with the function key mappings
for those items which have them:
.PP
.\" function keys are listed first, by analogy with short options
.\" being listed the same way.
.\"
.I F3
.br
.I "File, Open Snapshot..."
.RS
Load a snapshot (of machine state, memory contents etc.), which should
be in Z80, SNA, or SLT format. See the
.B "FILE SELECTION"
section below for details on how to choose the file.
.RE
.PP
.I F2
.br
.I "File, Save Snapshot..."
.RS
Save a snapshot in Z80 format. The GTK+ UI lets you select a filename,
but the others just write the file as
.IR snapshot.z80 ,
and have a differently-named menu item to match.
.RE
.PP
.I "Recording, Record..."
.RS
Start recording input to an RZX file. Again, the GTK+ UI lets you
select a filename, whilst the others just write to
.IR record.rzx
.RE
.PP
.I "Recording, Play..."
.RS
Playback recorded input from an RZX file. This lets you replay
keypresses recorded previously. RZX files generally contain a snapshot
with the Spectrum's state at the start of the recording; if the
selected RZX file doesn't, you'll be prompted for a snapshot to load
as well.
.RE
.PP
.I "Recording, Stop"
.RS
Stop any currently-recording/playing RZX file.
.RE
.PP
.I F10
.br
.I "File, Exit"
.RS
Exit the emulator.
.RE
.PP
.I F4
.br
.I "Options, General..."
.RS
Display the General Options dialog, letting you configure Fuse. (With
the widget UI, the keys shown in brackets toggle the options,
.I Enter
confirms any changes, and
.I Esc
aborts.) Note that any changed settings only apply to the
currently-running Fuse.
.PP
The options available are:
.PP
.I "Issue 2 keyboard"
.RS
Early versions of the Spectrum used a different value for unused bits
on the keyboard input ports, and a few games depended on the old value
of these bits. Enabling this option switches to the old value, to let
you run them.
.RE
.PP
.I "Kempston joystick"
.RS
There were several types of joystick interface for the Spectrum;
enabling this option lets you use what was probably the most
widely-supported one. When enabled, the joystick uses the keys
.IR q ,
.IR a ,
.IR o ,
.IR p ,
and
.IR Space .
The use of
.I Space
as the fire button can cause problems with some games - since the keys
still form part of the emulated Spectrum's keyboard, and
.I Space
was sometimes used as a second fire button when using the joystick -
so it's probably best to only enable Kempston emulation when you
really need it.
.RE
.PP
.I "Use tape traps"
.RS
Ordinarily, Fuse intercepts calls to the ROM tape-loading routine in
order to load from tape files more quickly when possible. But this can
(rarely) interfere with TZX loading; disabling this option avoids the
problem at the cost of slower (i.e. always real-time) tape-loading.
When tape-loading traps are disabled, you need to start tape playback
manually, by pressing
.I F8
or choosing the
.I "Tape, Play"
menu item.
.RE
.PP
.I "Use .slt traps"
.RS
The multi-load aspect of SLT files requires a trap instruction to be
supported. This instruction is not generally used except for this
trap, but since it's not inconceivable that a program could be wanting
to use the real instruction instead, you can choose whether to support
the trap or not.
.RE
.RE
.PP
.I "Options, Sound..."
.RS
Display the Sound Options dialog, letting you configure Fuse's sound
output. (With the widget UI, the keys shown in brackets toggle the
options,
.I Enter
confirms any changes, and
.I Esc
aborts.) Note that any changed settings only apply to the
currently-running Fuse.
.PP
.I "Sound enabled"
.RS
Specify whether sound output should be enabled at all. When this
option is disabled, Fuse will not make any sound.
.RE
.PP
.I "Loading sound"
.RS
Normally, Fuse emulates tape-loading noise when loading from TAPs or
TZXs in real-time, albeit at a deliberately lower volume than on a
real Spectrum. You can disable this option to eliminate the loading
noise entirely.
.RE
.PP
.I "AY stereo separation"
.RS
By default, the sound output is mono, since this is all you got from
an unmodified Spectrum. But enabling this option gives you so-called
ACB stereo (for sound from the 128's AY-3-8912 sound chip). This
actually works a little better than ACB stereo modifications for the
machine itself, since it uses stereo positioning rather than simply
playing on one channel only.
.RE
.PP
.I "Beeper pseudo-stereo"
.RS
The Spectrum beeper is inherently mono, but enabling this option adds
a simple fake-stereo effect. While the slight echo involved can
sometimes make beeper noise sound worse, in many cases it gives an
acceptable result.
.RE
.PP
.I F5
.br
.I "Machine, Reset"
.RS
Reset the emulated Spectrum.
.RE
.PP
.I F9
.br
.I "Machine, Select..."
.RS
Choose a type of Spectrum to emulate. The machine initially emulated
is the 48K Spectrum. The choices available are 48K, 128K, +2, +2A, +3,
and TC2048 but most of the time you'll probably want to use the 48 or
128 machines.
.RE
.PP
.I F7
.br
.I "Tape, Open..."
.RS
Choose a TAP or TZX virtual-tape file to load from. See the
.B "FILE SELECTION"
section below for details on how to choose the file. The loading does
not start automatically - you have to start the load in the emulated
machine (with LOAD "" or the 128's Tape Loader option, though you may
need to reset first).
.PP
To
.I guarantee
that TZX files will load properly, you should select the file, make
sure tape-loading traps are disabled in the General Options dialog,
then press
.I F8
(or do
.IR "Tape, Play" ).
That said, most TZXs will work with tape-loading traps enabled (often
quickly loading partway, then loading the rest real-time), so you
might want to try it that way first.
.RE
.PP
.I F8
.br
.I "Tape, Play"
.RS
Start playing the TAP or TZX file, if required. (Choosing the option
(or pressing
.IR F8 )
again pauses playback, and a further press resumes.) To explain - if
tape-loading traps have been disabled (in the General Options dialog),
starting the loading process in the emulated machine isn't enough. You
also have to `press play', so to speak :-), and this is how you do
that. You may also need to `press play' like this in certain other
circumstances, e.g. TZXs containing multi-load games may have a
stop-the-tape request (which Fuse obeys).
.RE
.PP
.I "Tape, Rewind"
.RS
Rewind the current virtual tape, so it can be read again from the
beginning.
.RE
.PP
.I "Tape, Clear"
.RS
Clear the current virtual tape. This is particularly useful when you
want a `clean slate' to add newly-saved files to, before doing
.I "Tape, Write..."
(or
.IR F6 ).
.RE
.PP
.I F6
.br
.I "Tape, Write..."
.RS
Write the current virtual-tape contents to a TZX file. The GTK+ UI
lets you select a filename (see
.B "FILE SELECTION"
below), the others just write the file as
.IR tape.tzx ,
and have a slightly different menu item. The virtual-tape contents are
the contents of the previously-loaded tape (if any has been loaded
since you last did a
.IR "Tape, Clear" ),
followed by anything you've saved from the emulated machine since.
These newly-saved files are
.I not
written to any tape file until you choose this option!
.RE
.PP
.I "Disk"
.RS
Note that the Disk menu and associated submenus are available only if
Fuse was compiled with +3 support. (This won't have happened if the
`lib765' library couldn't be found at compile time.) Even then, the
virtual disk images are only accessible when emulating a +3. (See
.B "THE .DSK FORMAT"
section below for notes on the file formats supported).
.RE
.PP
.I "Disk, Drive A:, Insert"
.RS
Select a disk-image file (in DSK format) to read/write in the emulated
+3's drive A:. Currently Fuse provides no way to create these files,
though it's possible to format an existing one from the emulated +3.
.PP
Both emulated drives are the 3" type (in effect, the internal drive
plus an external FD-1). With the usual +3 format, these have a
capacity of 173K.
.RE
.PP
.I "Disk, Drive A:, Eject"
.RS
Deselect the disk image currently in drive A: - or from the +3's
perspective, eject it.
.RE
.PP
.I "Disk, Drive B:, Insert"
.RS
As above, but for drive B:.
.RE
.PP
.I "Disk, Drive B:, Eject"
.RS
As above, but for drive B:.
.RE
.PP
.I "Help, Keyboard picture..."
.RS
Display a diagram showing the Spectrum keyboard, and the various
keywords that can be generated with each key from (48K) BASIC. The
picture remains onscreen (and the emulator paused) until you press
.I Esc
or
.IR Enter .
.RE
.PP
.\"
.\"------------------------------------------------------------------
.\"
.SH "KEY MAPPINGS"
When emulating the Spectrum, keys
.I F1
to
.I F10
are used as shortcuts for various menu items, as described above. The
alphanumeric keys (along with
.I Enter
and
.IR Space )
are mapped as-is to the Spectrum keys. The other key mappings are:
.TP
.I Shift
emulated as Caps Shift
.TP
.IR Control ", " Alt ", and " Meta
emulated as Symbol Shift (most other modifiers are also mapped to
this)
.TP
.I Backspace
emulated as Caps-0 (Delete)
.TP
.I Esc
emulated as Caps-1 (Edit)
.TP
.I Caps Lock
emulated as Caps-2
.TP
.I Cursor keys
emulated as Caps-5/6/7/8 (as appropriate)
.PP
Some further punctuation keys are supported, if they exist on your
keyboard -
.RI ` , ',
.RI ` . ',
.RI ` / ',
.RI ` ; ',
.RI ` ' ',
.RI ` # ',
.RI ` - ',
and
.RI ` = '.
These are mapped to the appropriate symbol-shifted keys on the
Spectrum.
.PP
A list of keys applicable when using the file selection dialogs is
given in the
.B "FILE SELECTION"
section below.
.\"
.\"------------------------------------------------------------------
.\"
.SH "DISPLAY SIZE"
Some of Fuse's UIs allow resizing of the emulated Spectrum's display.
Since these are the window-based ones (GTK+ and Xlib), you can resize
the window by, well, resizing it. :-) You do have to make the window
twice the width before the Fuse window actually scales up; you don't
.I have
to make it twice the height as well, but generally you'd want to.
.\"
.\"------------------------------------------------------------------
.\"
.SH "THE EMULATED SPECTRUM"
The emulated Spectrum is, by default, an unmodified 48K Spectrum with
a tape player and ZX Printer attached. Oh, and apparently some magical
snapshot load/save machine which is probably best glossed over for the
sake of the analogy. :-)
.PP
To emulate different kinds of Spectrum, select the
.I "Machine, Select..."
menu option, or press
.IR F9 .
.PP
The Spectrum emulation is paused when any dialogs appear. In the
widget UI, it's also paused when menus or the keyboard picture are
displayed.
.\"
.\"------------------------------------------------------------------
.\"
.SH "PRINTER EMULATION"
The various models of Spectrum supported a range of ways to connect
printers, three of which are supported by Fuse. Different printers are
made available for the different models:
.TP
.IR 48 ", " TC2048
ZX Printer
.TP
.IR 128 / +2
Serial printer (text-only)
.TP
.IR +2A ", " +3
Parallel printer (text-only)
.PP
Any printout is appended to one (or both) of two files, depending on
the printer -
.I printout.txt
for text output, and
.I printout.pbm
for graphics. (PBM images are supported by most image viewers and
converters.) While the ZX Printer can
.I only
output graphically, simulated text output is generated at the same
time using a crude sort of OCR based on the current character set (a
bit like using SCREEN$). There is currently no support for graphics
when using the serial/parallel output, though any escape codes used
will be `printed' faithfully. (!)
.PP
By the way, it's not a good idea to modify the
.I printout.pbm
file outside of Fuse if you want to continue appending to it. The
header needs to have a certain layout for Fuse to be able to continue
appending to it correctly, and the file will be overwritten if it
can't be appended to.
.\"
.\"------------------------------------------------------------------
.\"
.SH "FILE SELECTION"
The way you select a file (whether snapshot or tape file) depends on
which UI you're using. So firstly, here's how to use the GTK+ file
selector.
.PP
The selector shows the directories and files in the current directory
in two separate subwindows. If either list is too big to fit in the
window, you can use the scrollbar to see the rest (by dragging the
slider, for example), or you can use
.I Shift-Tab
(to move the keyboard focus to a subwindow) and use the cursor keys.
To change directory, double-click it.
.PP
To choose a file to load you can either double-click it, or click it
then click
.IR Ok .
Or click
.I Cancel
to abort.
.PP
If you're using the keyboard, probably the easiest way to use the
selector is to just ignore it and type in the name. This isn't as
irksome as it sounds, since the filename input box has filename
completion - type part of a directory or file name, then press
.IR Tab .
It should complete it. If it was a directory, it moves to that
directory; if the completion was ambiguous, it completes as much as
possible, and narrows the filenames shown to those which match. You
should press
.I Enter
when you've finished typing the filename, or
.I Esc
to abort.
.PP
Now, if you're using the widget UI - the one using the Spectrum font -
the selector works a bit differently. The files and directories are
all listed in a single two-column-wide window (the directories are
shown at the top, ending in `/') - the names may be truncated onscreen
if they're too long to fit.
.PP
To move the cursor, you can either use the cursor keys, or the
Spectrum equivalents
.\" too many to portably risk using IR...
\fI5\fR/\fI6\fR/\fI7\fR/\fI8\fR, or (similarly)
\fIh\fR/\fIj\fR/\fIk\fR/\fIl\fR. For faster movement, the
.IR "Page Up" ,
.IR "Page Down" ,
.IR Home ,
and
.I End
keys are supported and do what you'd expect. To select a file or
directory, press
.IR Enter .
To abort, press
.I Esc
(or
.IR 1 ).
.PP
With both selectors, do bear in mind that
.I all
files are shown, whether Fuse would be able to load them or not.
.\"
.\"------------------------------------------------------------------
.\"
.SH THE .DSK FORMAT
.PP
In general, disk images for the +3 Spectrum are thought of as being in
DSK format. However, this is actually an slight oversimplification;
there in in fact
.I two
similar, but not identical, DSK formats. (The difference can be seen
by doing `head -1
.IR dskfile ':
one format will start `MV - CPCEMU' and the other will start
`EXTENDED'.)
.PP
The `lib765' library used by Fuse to emulate the +3's FDC supports the
`CPCEMU' format, but not the extended format. If the `libdsk' library
was also found whilst compiling Fuse, this is used to provide support
for the extended format, as well as for other goodies such as gzip
compressed disk images.
.\"
.\"------------------------------------------------------------------
.\"
.SH BUGS
Not many peripherals are supported.
.\"
.\"------------------------------------------------------------------
.\"
.SH SEE ALSO
.IR tzxlist "(1),"
.IR rzxdump "(1),"
.IR rzxtool "(1),"
.IR xspect "(1),"
.IR xzx "(1)"
.PP
The comp.sys.sinclair Spectrum FAQ, at
.br
.IR "http://www.srcf.ucam.org/~pak21/cssfaq/index.html" .
.\"
.\"------------------------------------------------------------------
.\"
.\" `AUTHOR' here is deliberate; avoiding the plural IMHO makes it
.\" clear that Phil is the main author.
.\"
.SH AUTHOR
Philip Kendall (pak21-fuse@srcf.ucam.org).
.PP
Matan Ziv-Av wrote the svgalib and framebuffer UIs, the glib
replacement code, and did some work on the OSS-specific sound code and
the original widget UI code.
.PP
Russell Marks wrote the sound emulation and OSS-specific sound code,
the joystick emulation, some of the printer code, and this man page.
.PP
John Elliott's lib765 library emulates the +3's disk controller chip,
providing Fuse's +3 disk support, and his libdsk library provides
support for more disk image formats.
.PP
Ian Collier wrote the ZX Printer emulation (for xz80).
.PP
Darren Salt wrote the original versions of the code for +3 emulation,
SLT support, MITSHM support (for the Xlib UI), TZX raw data blocks,
and RZX embedded snapshots and compression.
.PP
Alexander Yurchenko wrote the OpenBSD/Solaris-specific sound code.
.PP
Frederick Meunier wrote the TC2048 support
