#define T_AND                            1
#define T_OR                             2
#define T_UNION                          3
#define T_EQ                             4
#define T_NE                             5
#define T_GT                             6
#define T_GE                             7
#define T_LT                             8
#define T_LE                             9
#define T_MATCH                         10
#define T_NOT                           11
#define T_LABEL                         12
#define T_ROOT                          13
#define T_THIS                          14
#define T_DOT                           15
#define T_WILDCARD                      16
#define T_BROPEN                        17
#define T_BRCLOSE                       18
#define T_BOOL                          19
#define T_NUMBER                        20
#define T_STRING                        21
#define T_REGEXP                        22
#define T_POPEN                         23
#define T_PCLOSE                        24
