#!/usr/bin/perl -w

use strict;

use lib '../../perl';

use Fuse;
use Fuse::Dialog;

die "No data file specified" unless @ARGV;

my @dialogs = Fuse::Dialog::read( shift @ARGV );

print Fuse::GPL( 'options.h: options dialog boxes',
		 '2001-2002 Philip Kendall' ) . << "CODE";

/* This file is autogenerated from options.dat by options-header.pl.
   Do not edit unless you know what you\'re doing! */

#ifndef FUSE_GTKOPTIONS_H
#define FUSE_GTKOPTIONS_H

#ifndef __GTK_H__
#include <gtk/gtk.h>
#endif

CODE

foreach( @dialogs ) {

    print << "CODE";
void gtkoptions_$_->{name}( GtkWidget *widget, gpointer data );

typedef struct gtkoptions_$_->{name}_t \{

  GtkWidget *dialog;

CODE

    foreach my $widget ( @{ $_->{widgets} } ) {

	if( $widget->{type} eq "Checkbox" ) {
	    print "  GtkWidget *$widget->{value};\n";
	}

    }

    print "\n} gtkoptions_$_->{name}_t;\n\n"
}

print << "CODE";
#endif				/* #ifndef FUSE_GTKOPTIONS_H */
CODE
