#!/usr/bin/perl -w

use strict;

use English;

$INPUT_RECORD_SEPARATOR = "";		# Paragraph mode

print << "CODE";
/* options.h: options dialog boxes
   Copyright (c) 2001-2002 Philip Kendall

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 49 Temple Place, Suite 330, Boston, MA 02111-1307 USA

   Author contact information:

   E-mail: pak21-fuse\@srcf.ucam.org
   Postal address: 15 Crescent Road, Wokingham, Berks, RG40 2DB, England

*/

/* This file is autogenerated from options-header.dat by options.pl.
   Do not edit unless you know what you\'re doing! */

#ifndef FUSE_GTKOPTIONS_H
#define FUSE_GTKOPTIONS_H

#ifndef __GTK_H__
#include <gtk/gtk.h>
#endif

CODE

while(<>) {

    my( $type, $title, @widgets ) = split /\n/;

    print "void gtkoptions_${type}( GtkWidget *widget, gpointer data );\n";

}

print << "CODE";

#endif				/* #ifndef FUSE_GTKOPTIONS_H */
CODE
