#!/usr/bin/perl -w

use strict;

use lib '../perl';

use Fuse;
use Fuse::Dialog;

die "No data file specified" unless @ARGV;

my @dialogs = Fuse::Dialog::read( shift @ARGV );

print Fuse::GPL( 'options.h: options dialog boxes',
		 '2001-2002 Philip Kendall' ) . << "CODE";

/* This file is autogenerated from options.dat by options-header.pl.
   Do not edit unless you know what you\'re doing! */

#ifndef FUSE_WIDGETOPTIONS_H
#define FUSE_WIDGETOPTIONS_H

#ifndef FUSE_SETTINGS_H
#include "settings.h"
#endif

#ifndef FUSE_WIDGET_H
#include "widget.h"
#endif

extern settings_info widget_options_settings;

CODE

foreach( @dialogs ) {

    print << "CODE";
int widget_$_->{name}_draw( void *data );
void widget_$_->{name}_keyhandler( keyboard_key_name key );

CODE
}

print << "CODE";
#endif				/* #ifndef FUSE_WIDGETOPTIONS_H */
CODE
