name: Fuse App For Linux
run-name: Build Fuse App for Linux / ${{ github.actor }} /

# Executed upon each commit pushed, merge commit in PR
on: [pull_request]

jobs:
  libspectrum:
    # Build libspectrum from the canonical SourceForge repository.
    name: "Libspectrum lib (Linux)"
    uses: ./.github/workflows/build_libspectrum_linux_sub.yml
    with:
      key: fuse-app
      libspectrum_ref: master
      use_fake_glib: true

  libspectrum-gtk:
    name: "Libspectrum lib for GTK (Linux)"
    uses: ./.github/workflows/build_libspectrum_linux_sub.yml
    with:
      key: fuse-app-gtk
      libspectrum_ref: master
      use_fake_glib: false

  # Default build without any configure params (xlib)
  default-ui:
    name: "Fuse Default UI (Linux)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: Default
      dependencies: "libaudiofile-dev libgcrypt-dev xorg-dev"
      configure_params: ""
      verify_ui: "xlib"

#########################################
### SUPPORTED Linux UI configurations ###
#########################################

  # NULL UI
  null-ui:
    name: "Fuse NULL UI (Linux)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: "NULL UI"
      dependencies: "libaudiofile-dev libgcrypt-dev libpng-dev"
      configure_params: "--with-null-ui"
      verify_ui: "null"
      run_check: true

  # GTK 3 UI
  gtk3-ui:
    name: "Fuse GTK 3 UI (Linux)"
    needs: [libspectrum-gtk]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: GTK3 UI
      dependencies: "libaudiofile-dev libgcrypt-dev gtk3.0 libgtk-3-dev"
      configure_params: "--with-gtk"
      libspectrum_key: fuse-app-gtk
      verify_ui: "gtk"
      verify_other: "Using GTK 3: yes"

  # SDL 1 UI + Sound
  sdl1-ui:
    name: "Fuse SDL 1 UI + sound (Linux)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: SDL1 UI
      dependencies: "libaudiofile-dev libgcrypt-dev libsdl1.2-dev libpng-dev"
      configure_params: "--with-sdl --disable-sdl2"
      verify_ui: "sdl"
      verify_audio: "sdl"
      verify_other: "Using SDL 1: yes"

  # SDL 2 UI + Sound
  sdl2-ui:
    name: "Fuse SDL 2 UI + sound (Linux)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: SDL2 UI
      dependencies: "libaudiofile-dev libgcrypt-dev libsdl2-dev libpng-dev"
      configure_params: "--with-sdl2"
      verify_ui: "sdl2"
      verify_audio: "sdl2"
      verify_other: "Using SDL 2: yes"

##########################################
### DEPRECATED Linux UI configurations ###
##########################################

  # FB UI (deprecated)
  fb-ui:
    name: "Fuse FB UI (Linux) (deprecated)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: "FB UI (deprecated)"
      dependencies: "libaudiofile-dev libgpm-dev libgcrypt-dev libpng-dev"
      configure_params: "--with-fb"
      verify_ui: "fb"

  # XLIB UI (deprecated)
  xlib-ui:
    name: "Fuse X-lib UI (Linux) (deprecated)"
    needs: [libspectrum]
    uses: ./.github/workflows/build_linux_sub.yml
    with:
      name: X-lib UI (deprecated)
      dependencies: "libaudiofile-dev libgcrypt-dev xorg-dev"
      configure_params: "--with-x"
      verify_ui: "xlib"
