name: Nightly build
run-name: Automated nightly build and pre-release

# Executed every night (1 AM) + button
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  # Merge master from defined repo (usually official fuse repo)
  catchup:
    name: "Merge foreign master"
    runs-on: ubuntu-latest
    if: ${{ vars.PARENT_FUSE_BRANCH }} && ${{ vars.PARENT_FUSE_REPO }}
    permissions:
      contents: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: "Merge fresh ${{ vars.PARENT_FUSE_BRANCH }} from ${{ vars.PARENT_FUSE_REPO }}"
        run: |
          git fetch --prune
          git remote add repo ${{ vars.PARENT_FUSE_REPO }}
          git fetch repo
          git merge repo/${{ vars.PARENT_FUSE_BRANCH }}
          git push

  # Build and release nightly prerelease version from master (no draft)
  # Add current date and time to the tag, keep latest 5
  master:
    needs: [catchup]
    name: "Nightly build from master"
    uses: ./.github/workflows/test_release.yml
    with:
      reason: "Nightly master build"
      draft: false
      generateReleaseNotes: true
      libspectrum_branch: "master"
      add_date_time: true
      keep_latest: 5
    secrets:
      RELEASE_TOKEN: "${{ secrets.RELEASE_TOKEN }}"
